# Generated by Django 2.0.6 on 2018-07-14 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
