# Generated by Django 2.0.6 on 2018-07-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerador', '0002_auto_20180714_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='image',
            field=models.FileField(upload_to='media/%Y/%m/%d/'),
        ),
    ]
