# Generated by Django 2.0.6 on 2018-07-19 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerador', '0004_auto_20180715_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
